config/routes.rb
Rails.application.routes.draw do
  get 'contacts/new'

  get 'contacts/thanks'

  root 'snippets#index'
  get 'snippets/tags/:tag_name' => 'snippets#tagged', as: :snippet_tag
  get '/contact' => 'contacts#new', as: :contact
  post '/contact' => 'contacts#create', as: :contact_forms
  get '/thanks' => 'contacts#thanks', as: :thanks

  get 'snippets/new'

end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,      :validate => true



  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "bharvi@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base
  acts_as_taggable
  include PgSearch
  pg_search_scope :mysearch,
                  :against => [:author, :quote],
                  using: {
                    tsearch: {dictionary: "english"}
                  }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(params[:contact_form])
    if @contact_form.valid?
      @contact_form.deliver
      redirect_to thanks_path
    else
      render :new
    end

  end

  def thanks
    render :thanks
  end
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController
  before_action do
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def index
    @snippets = Snippet.all
    @snippets = @snippets.mysearch(params[:search]) if params[:search].present?
  end

  def tagged
    @snippets = Snippet.tagged_with(params[:tag_name])
    render :index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/snippets_helper.rb
module SnippetsHelper
end

app/views/contacts/new.html.erb
<div class="page-header">
  <h1>We will be happy to publish your quotes!! <small>Please contact us !</small></h1>
</div>

<%= simple_form_for @contact_form do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :message, as: :text %>
  <%= f.submit class: "btn btn-primary btn-lg" %>
<% end %>

app/views/contacts/thanks.html.erb
<div class = "page-header">
<h1>Thanks for Choosing us.</h1>
<p>Someone will contact you real soon !</p>

<%= link_to "Home", root_path %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Snippets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="container">

<nav>
<div class="row">
  <div class="col-xs-8">
    <%= form_tag root_path, method: 'get' do %>
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
    <% end %>
  </div>
  <div class="col-xs-4">
    <div class="pull-right">
      <p>
        <%= link_to "Contact Us", contact_path, class: "btn btn-default" %>
      </p>

    </div>
  </div>
</div>
</nav>

<%= yield %>
</div>
</body>
</html>

app/views/snippets/index.html.erb
<h1>Listing Quotes</h1>
<p>
<% @snippets.each do |snippet| %>

        <h3><%= highlight(snippet.author, params[:search]) %></h3>
        <i class="fa fa-quote-left fa-1x pull-left fa-border"></i>


        <p> <%= highlight(snippet.quote, params[:search]) %>
        <i class="fa fa-quote-right fa-1x  fa-border"></i></p>


<p>Tags: <%= raw snippet.tag_list.map { |t| link_to t, snippet_tag_path(t) }.join(', ') %></p>        
<p><br><br>
</p>



<% end %>

app/views/snippets/new.html.erb
<h1>Snippets#new</h1>
<p>Find me in app/views/snippets/new.html.erb</p>